### ISSUE TITLE
Introduce a custom URL proxy

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/btfhub#11]
We would like to introduce a flexible URL API that will be the primary interface to obtain BTF files.
For example: `https://archive.btfhub.io/v1/ubuntu/20.04/x86_64/5.11.0-1007-azure.btf.tar.xz` -> `https://raw.githubusercontent.com/aquasecurity/btfhub/main/archive/ubuntu/20.04/x86_64/5.11.0-1007-azure.btf.tar.xz`.

Motivations:
1. API stability, backwards/forwards compatibility: A custom API that can be detached from the filesystem structure and would allow us to evolve the filesystem without breaking users. By introducing an API version to the URL (`/v1`) we can also evolve the public facing api without breakage. 
2. Decouple storage: currently we are using the same git repo to store the generation script and all generated artifacts. We have experimented with git LFS, which caused a hiccup and then reverted back. We are now considering using a robust external storage such as s3. An API would allow us to choose the best storage without affecting users. Additionally, as Aqua and others start use btfhub for production-level business applications, we might want to introduce some form of HA redundancy, which will be easier with an independent API.
3. User experience: with a customizable API we would be able to provide multiple access pattern or more sophisticated expressions in the API.

**Comment by rafaeldtinoco** [comment]
This has been sorted out by btfhub-online project. We have an integration already in place for Tracee.
