### ISSUE TITLE
lack of documentation for latest changes

### ISSUE THREAD

**Issue by guyarb** [aquasecurity/btfhub#16]
up until now i  used `./btfgen.sh <core.o>` to generate the BTF files for my code
but now  i need to run `./extract.sh` first
i didn't see any reference in the documentation for that change

**Comment by guyarb** [comment]
as i understand, we need to run `extract.sh` before, but that's not documented in the readme.
can you please update the readme with the correct steps?

**Comment by guyarb** [comment]
furthermore, i've started to have `WARN: btf for ./custom-archive/ubuntu/20.04/x86_64/5.4.0-1049-aws.btf is poisoned` messages for most of btf files

**Comment by rafaeldtinoco** [comment]
Hello @guyarb, Let me try to help you through here then...

For the first statement:

* Yes, you have to run extract.sh before running btfgen.sh. This has been always the case, not sure how you were able to run btfgen.sh without extracting .tar.xz files first. 

> Note that BTFHub is currently in Beta state and there are not releases yet, thus we're not guaranteeing a way of using it until the first release. To cope with that, you may stick to a specific commit with the behavior you had, and then make the needed changes once we release its initial version.

Nevertheless, the correct way of using btfhub (currently) is:

```
[rafaeldtinoco@fujitsu:~/.../ebpf/btfhub]$ ./tools/extract.sh -a $(uname -m)
```

and wait for all the BTF files to be extracted, then to run btfgen.sh for a specific BPF object:

```
[rafaeldtinoco@fujitsu:~/.../ebpf/btfhub]$ sudo ./tools/btfgen.sh -a $(uname -m) -o /home/rafaeldtinoco/work/sources/ebpf/tracee/tracee-ebpf/dist/tracee.bpf.core.o
centos/7/x86_64
SBTF: ./archive/centos/7/x86_64/3.10.0-862.el7.x86_64.btf
OBJ : /home/rafaeldtinoco/work/sources/ebpf/tracee/tracee-ebpf/dist/tracee.bpf.core.o
DBTF: ./custom-archive/centos/7/x86_64/3.10.0-862.el7.x86_64.btf
WARN: btf for ./custom-archive/centos/7/x86_64/3.10.0-862.el7.x86_64.btf is poisoned
SBTF: ./archive/centos/7/x86_64/3.10.0-1160.45.1.el7.x86_64.btf
OBJ : /home/rafaeldtinoco/work/sources/ebpf/tracee/tracee-ebpf/dist/tracee.bpf.core.o
DBTF: ./custom-archive/centos/7/x86_64/3.10.0-1160.45.1.el7.x86_64.btf
WARN: btf for ./custom-archive/centos/7/x86_64/3.10.0-1160.45.1.el7.x86_64.btf is poisoned
SBTF: ./archive/centos/7/x86_64/3.10.0-693.5.2.el7.x86_64.btf
OBJ : /home/rafaeldtinoco/work/sources/ebpf/tracee/tracee-ebpf/dist/tracee.bpf.core.o
DBTF: ./custom-archive/centos/7/x86_64/3.10.0-693.5.2.el7.x86_64.btf
```

For your second statement, on the poisoned messages.

This means that, for that particular kernel version, your code wouldn't be able to run with the generated BTF (and possibly with the vanilla BTF file as well). This is expected if you're using latest features of eBPF... it means that libbpf wasn't able to do the relocations your code needed. 

The "btfgen" binaries have an option now not to write result BTF files if they were poisoned. You can change btfgen.sh script not use that option and still generate the final BTF files with poisoned instructions, although you wouldn't be able to use them most likely (as when loading your eBPF object using those BTFs, the verifier will complain about poisoned instructions. 

Let me know if you need any other information, I'll be glad to help.

**Comment by guyarb** [comment]
oh i missed the "beta alert"
thank you for the clarification and the help!
