### ISSUE TITLE
To cover most used k8s public cloud kernels

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/btfhub#23]
To use as input the following issue:

https://github.com/aquasecurity/tracee/issues/1022

and to make sure we are covering the most common k8s public cloud kernels there are.

**Comment by itaysk** [comment]
we got a strong requirement to add GKE Ubuntu Focal (we already have aws and azure)

**Comment by rafaeldtinoco** [comment]
> we got a strong requirement to add GKE Ubuntu Focal (we already have aws and azure)

Done by:

https://github.com/aquasecurity/btfhub/commit/45c3e8c52fcdbd1f77a6f4e2403add7111255750

and:

https://github.com/aquasecurity/btfhub/actions/runs/1689764680

And committed in btfhub-archive by:

https://github.com/aquasecurity/btfhub-archive/commit/4bb94b53a764d57ff46a65e899840db0b98be86e

$ git log -1 -p | diffstat -l
18.04/x86_64/4.15.0-1030-gke.btf.tar.xz
18.04/x86_64/4.15.0-1032-gke.btf.tar.xz
18.04/x86_64/4.15.0-1033-gke.btf.tar.xz
18.04/x86_64/4.15.0-1034-gke.btf.tar.xz
18.04/x86_64/4.15.0-1036-gke.btf.tar.xz
18.04/x86_64/4.15.0-1037-gke.btf.tar.xz
18.04/x86_64/4.15.0-1040-gke.btf.tar.xz
18.04/x86_64/4.15.0-1041-gke.btf.tar.xz
18.04/x86_64/4.15.0-1042-gke.btf.tar.xz
18.04/x86_64/4.15.0-1044-gke.btf.tar.xz
18.04/x86_64/4.15.0-1045-gke.btf.tar.xz
18.04/x86_64/4.15.0-1046-gke.btf.tar.xz
18.04/x86_64/4.15.0-1048-gke.btf.tar.xz
18.04/x86_64/4.15.0-1049-gke.btf.tar.xz
18.04/x86_64/4.15.0-1050-gke.btf.tar.xz
18.04/x86_64/4.15.0-1052-gke.btf.tar.xz
18.04/x86_64/4.15.0-1055-gke.btf.tar.xz
18.04/x86_64/4.15.0-1057-gke.btf.tar.xz
18.04/x86_64/4.15.0-1058-gke.btf.tar.xz
18.04/x86_64/4.15.0-1059-gke.btf.tar.xz
18.04/x86_64/4.15.0-1063-gke.btf.tar.xz
18.04/x86_64/4.15.0-1064-gke.btf.tar.xz
18.04/x86_64/4.15.0-1066-gke.btf.tar.xz
18.04/x86_64/4.15.0-1067-gke.btf.tar.xz
18.04/x86_64/4.15.0-1069-gke.btf.tar.xz
18.04/x86_64/4.15.0-1070-gke.btf.tar.xz
18.04/x86_64/4.15.0-1072-gke.btf.tar.xz
18.04/x86_64/4.15.0-1073-gke.btf.tar.xz
18.04/x86_64/4.15.0-1076-gke.btf.tar.xz
18.04/x86_64/4.15.0-1077-gke.btf.tar.xz
18.04/x86_64/4.15.0-1078-gke.btf.tar.xz
18.04/x86_64/4.15.0-1079-gke.btf.tar.xz
18.04/x86_64/5.4.0-1025-gke.btf.tar.xz
18.04/x86_64/5.4.0-1027-gke.btf.tar.xz
18.04/x86_64/5.4.0-1029-gke.btf.tar.xz
18.04/x86_64/5.4.0-1032-gke.btf.tar.xz
18.04/x86_64/5.4.0-1033-gke.btf.tar.xz
18.04/x86_64/5.4.0-1035-gke.btf.tar.xz
18.04/x86_64/5.4.0-1036-gke.btf.tar.xz
18.04/x86_64/5.4.0-1037-gke.btf.tar.xz
18.04/x86_64/5.4.0-1039-gke.btf.tar.xz
18.04/x86_64/5.4.0-1040-gke.btf.tar.xz
18.04/x86_64/5.4.0-1042-gke.btf.tar.xz
18.04/x86_64/5.4.0-1043-gke.btf.tar.xz
18.04/x86_64/5.4.0-1044-gke.btf.tar.xz
18.04/x86_64/5.4.0-1046-gke.btf.tar.xz
18.04/x86_64/5.4.0-1049-gke.btf.tar.xz
18.04/x86_64/5.4.0-1051-gke.btf.tar.xz
18.04/x86_64/5.4.0-1052-gke.btf.tar.xz
18.04/x86_64/5.4.0-1053-gke.btf.tar.xz
18.04/x86_64/5.4.0-1054-gke.btf.tar.xz
18.04/x86_64/5.4.0-1055-gke.btf.tar.xz
18.04/x86_64/5.4.0-1056-gke.btf.tar.xz
18.04/x86_64/5.4.0-1057-gke.btf.tar.xz
20.04/x86_64/5.4.0-1033-gke.btf.tar.xz
20.04/x86_64/5.4.0-1035-gke.btf.tar.xz
20.04/x86_64/5.4.0-1036-gke.btf.tar.xz
20.04/x86_64/5.4.0-1037-gke.btf.tar.xz
20.04/x86_64/5.4.0-1039-gke.btf.tar.xz
20.04/x86_64/5.4.0-1041-gke.btf.tar.xz
20.04/x86_64/5.4.0-1042-gke.btf.tar.xz
20.04/x86_64/5.4.0-1043-gke.btf.tar.xz
20.04/x86_64/5.4.0-1044-gke.btf.tar.xz
20.04/x86_64/5.4.0-1046-gke.btf.tar.xz
20.04/x86_64/5.4.0-1049-gke.btf.tar.xz
20.04/x86_64/5.4.0-1051-gke.btf.tar.xz
20.04/x86_64/5.4.0-1052-gke.btf.tar.xz
20.04/x86_64/5.4.0-1053-gke.btf.tar.xz
20.04/x86_64/5.4.0-1054-gke.btf.tar.xz
20.04/x86_64/5.4.0-1055-gke.btf.tar.xz
20.04/x86_64/5.4.0-1056-gke.btf.tar.xz
20.04/x86_64/5.4.0-1057-gke.btf.tar.xz

**Comment by rafaeldtinoco** [comment]
This can be closed, there is no public cloud kernel that should be included in BTFHUB afaict.
