### ISSUE TITLE
centos and fedora BTFs coming from wrong kernels (need re-upload)

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/btfhub#3]
@mauriciovasquezbernal discovered that our BTFs for Fedora (and likely CentOS) are wrong. When comparing types of a running Fedora 31 and the BTFs we have for it, there are mismatches that should NOT be there. This happens because of different config options that change types (like task_struct) adding or removing fields.

By compiling latest dwarves from upstream in Fedora 31 and checking with:

```
$ pahole -E -C task_struct > from-sysfs.txt
$ pahole -Fdwarf -j external /usr/lib/debug/lib/modules/5.8.18-100.fc31.x86_64/vmlinux
$ pahole -E -C task_struct ./external > from-external.txt
$ diff from-sysfs.txt from-external.txt | wc -l
0
```
I discovered that I made a mistake when generating the BTFs. The RHEL-like distros have 2 kernels:

1. kernel (with kernel-debuginfo dbgsym pkg)
1. kernel-debug (with kernel-debug-debuginfo dbgsym pkg)

And I used the 2nd one, instead of the 1st, to generate the BTFs. Obviously those BTFs are not compatible as the kernel-debug has debug options enabled and its types are different than the vanilla kernel.

I'm changing the update.sh file to re-download all packages and re-generate the BTFs for CentOS and Fedora. This might take awhile, will be running in background and I'll close this issue when done.

**Comment by rafaeldtinoco** [comment]
@mauriciovasquezbernal, I have uploaded new BTF files for all fedora versions so you could test. After the debugging it was a trivial change (network bandwidth for the download mostly). I'm now running the BTFs for centos7 and centos8 again and will upload them as soon as they're read.

Feel free to test the new BTFs and please let me know if now they're the correct ones. Thanks for the feedback.

**Comment by mauriciovasquezbernal** [comment]
@rafaeldtinoco it works fine now! Thanks for the fix!
