### ISSUE TITLE
Add the `LICENSE` file to the archive repository

### ISSUE THREAD

**Issue by mrproliu** [aquasecurity/btfhub#33]
Hello, I am from the Apache SkyWalking community. By reading [this blog](https://kinvolk.io/blog/2022/03/btfgen-one-step-closer-to-truly-portable-ebpf-programs/), I learned that BTFGen can make eBPF programs portable. This is a great idea, and we'd love to add it to our [SkyWalking Rover project](https://github.com/apache/skywalking-rover).

However, during the integration, we found that the [btfhub-archive project](https://github.com/aquasecurity/btfhub-archive) did not add the `LICENSE` file, so we could not add it to the binary LICENSE statement file. So, could we help add the license file to this project?

You could get more information through [this PR](https://github.com/apache/skywalking-rover/pull/35). Hope to get your reply, thanks!

I saw that you closed the issue in the archive repository, so I created a new issue here to track :) @rafaeldtinoco

**Comment by rafaeldtinoco** [comment]
Working on it

**Comment by rafaeldtinoco** [comment]
Done by: https://github.com/aquasecurity/btfhub-archive/blob/main/LICENSE
