### ISSUE TITLE
Some Debian kernels are missing

### ISSUE THREAD

**Issue by Arignir** [aquasecurity/btfhub#35]
Hello,

I noticed some Debian kernels are missing:

Debian 9:
  - 4.9.0-18-amd64
  - 4.19.0-0.bpo.19-amd64

Debian 10:
  - 4.19.0-6-amd64
  - 4.19.0-8-amd64
  - 4.19.0-9-amd64
  - 4.19.0-12-amd64
  - 4.19.0-14-amd64
  - 4.19.0-16-amd64
  - 4.19.0-19-amd64

(And all of their variants)

Is this a mistake? Is their a reason why there's no BTF for them?

**Comment by rafaeldtinoco** [comment]
Fixed (https://github.com/aquasecurity/btfhub/pull/50#issuecomment-1359658866).
