### ISSUE TITLE
No Oracle Linux 7 kernels are included

### ISSUE THREAD

**Issue by acybere** [aquasecurity/btfhub#36]
Oracle Linux 7 kernels are missing.
Debug symbols for Oracle Linux kernels are at: https://oss.oracle.com/ol7/debuginfo/
OL release 7.8 is the first to ship with eBPF support according to documentation: https://docs.oracle.com/en/operating-systems/oracle-linux/7/relnotes7.8/ol7-features-changes.html#ol7-techpreview
[Those beginning kernels are](https://docs.oracle.com/en/operating-systems/oracle-linux/7/relnotes7.8/ol7-kernels.html):
- kernel-3.10.0-1127.el7
- kernel-uek-4.14.35-1902.300.11.el7uek

[A recent blog post](https://blogs.oracle.com/post/oracle-linux-and-bpf) indicates that newer releases provide BTFs. Assuming those are the latest available given the recentness of the blog post:
- kernel-3.10.0-1160.49.1.el7
- kernel-uek-5.4.17-2136.301.1.2.el7uek

BTFs for kernels between those versions may be produced for use.

**Comment by rafaeldtinoco** [comment]
Merged at: https://github.com/aquasecurity/btfhub/commit/26ec6014bd7340c3894f486db57a1ef0a712a3b0

**Comment by rafaeldtinoco** [comment]
Im generating the BTF files and uploading to archives soon.

**Comment by rafaeldtinoco** [comment]
@acybere have u generated all the BTF files or just tried with a few ?

![image](https://user-images.githubusercontent.com/7395852/187443764-d860d337-da2d-43a7-a497-10b402502b01.png)

I'm generating them for the past couple of days but pahole seems to be spending LOTS of time trying to parse DWARF from older kernels such as these. I tried latest pahole to see if it improved but no success. Just wondering if you faced the same issue.

**Comment by acybere** [comment]
I haven't seen it run to completion for generating them all. It is actually still running on my VM. It is quite slow. I do not know why. Looks like it's done with x86_64 with 299 (one failed) and made it through about 60 for arm64.

**Comment by rafaeldtinoco** [comment]
> @rafaeldtinoco I haven't seen it run to completion for generating them all. It is actually still running on my VM. It is quite slow. I do not know why. Looks like it's done with x86_64 with 299 (one failed) and made it through about 60 for arm64.

If you can get them all ready please put together a PR to the archive with them. I'll do the same if mine get ready. And then we do for amazon linux PR as well (after this one is merged and good). The updates (automatically run as cron) will be fine, the initial PR is the tricky one (to have done by github actions).

THanks

**Comment by acybere** [comment]
Archive PR created: https://github.com/aquasecurity/btfhub-archive/pull/5

**Comment by rafaeldtinoco** [comment]
Alright, to close this issue now, we should only make sure that the cron GitHub action will update btfhub-archive automatically if/when needed.

**Comment by rafaeldtinoco** [comment]
Oh, nm, I see the current kernels have BTF support now, right ? Just confirming (or else we should update Makefile to include recurrent checks for ol7 kernels).

**Comment by acybere** [comment]
@rafaeldtinoco I was wrong. We overlooked that additional patches for older kernels might still be released/maintained. See https://github.com/aquasecurity/btfhub/pull/45. We should continue checking for these for now.
