### ISSUE TITLE
archive folder structure and naming convention

### ISSUE THREAD

**Issue by acybere** [aquasecurity/btfhub#43]
The archive is inconsistent with naming and folder structure. Most follow the ID and VERSION or VERSION_ID (truncated to just the major version) fields of `/etc/os-release`. Oracle Linux 7 and amzn 1 (amazon 2018.03) currently do not follow that convention. Whether intentional or inadvertent, this is a solid convention to maintain.

> NAME="Amazon Linux AMI"
> VERSION="2018.03"
> ID="amzn"
> ID_LIKE="rhel fedora"
> VERSION_ID="2018.03"
> PRETTY_NAME="Amazon Linux AMI 2018.03"
> ANSI_COLOR="0;33"
> CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
> HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

> NAME="Oracle Linux Server"
> VERSION="7.9"
> ID="ol"
> ID_LIKE="fedora"
> VARIANT="Server"
> VARIANT_ID="server"
> VERSION_ID="7.9"
> PRETTY_NAME="Oracle Linux Server 7.9"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:oracle:linux:7:9:server"
> HOME_URL="https://linux.oracle.com/"
> BUG_REPORT_URL="https://bugzilla.oracle.com/"
> ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
> ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
> ORACLE_SUPPORT_PRODUCT="Oracle Linux"
> ORACLE_SUPPORT_PRODUCT_VERSION=7.9

**Comment by acybere** [comment]
https://github.com/aquasecurity/btfhub-archive/pull/9 already exists. I will create a PR with changes for `tools/update.sh` as well

**Comment by acybere** [comment]
https://github.com/aquasecurity/btfhub/pull/44 opened

**Comment by rafaeldtinoco** [comment]
Thanks @acybere , I have merged both an I believe this can be closed. Let me know if you need anything!
