### ISSUE TITLE
Scheduler failure for GCP Debian 10 with kernel version `4.19.0-22-cloud-amd64`

### ISSUE THREAD

**Issue by mrproliu** [aquasecurity/btfhub#48]
When creating a system using GCP Debian 10, I found that the kernel version is `4.19.0-22-cloud-amd64`. However, the BTF file for this version is currently missing from BTFHub.

I suspect that the failure of the scheduler in this project is preventing synchronization with the Debian system. It appears that the scheduler is unable to download the BTFHub project, potentially due to expired authorization.

Can you please assist with this issue? Thank you.

**Comment by rafaeldtinoco** [comment]
I'll take a look at this first thing in the week!! Sorry for the delay in answering!!

**Comment by rafaeldtinoco** [comment]
Hey @mrproliu sorry for not coming back to you soon. We were finishing tracee release before EOY and some EOY holidays now.. Either way, I'm scheduling some cron jobs to update the btfhub-archive for now (and will fix the automation when Im back from vacation). Thanks for your recent contributions, beginning next year I'll do a "full round review" over the repo, fixing outdated documentation, documenting scripts better, re-checking if all BTF files we have are really from kernels missing BTF info, etc.

Cheers!

**Comment by mrproliu** [comment]
Sure, take your time on this. This is an open-source project, so I won't force you to do anything. Thank you for providing such a great project :)

**Comment by rafaeldtinoco** [comment]
This is being taken care now that we have a new golang binary capable of managing the packages in the repository.

**Comment by rafaeldtinoco** [comment]
The cron.yaml workflow has been created and it is currently being updated to add more distributions (recently added).
