### ISSUE TITLE
Ubuntu Focal: HWE 5.11 kernels debug packages are broken in upstream

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/btfhub#5]
Due to some upstream issue, the 5.11 HWE kernels do not have their symbols published anywhere. If you check 'Packages' file from the ddebs.ubuntu.com repository you will find:

```
Package: linux-image-5.11.0-34-generic-dbgsym
Architecture: amd64
Version: 5.11.0-34.36~20.04.1
Priority: optional
Section: devel
Source: linux-signed-hwe-5.11
Maintainer: Canonical Kernel Team <kernel-team@lists.ubuntu.com>
Installed-Size: 23
Depends: linux-image-unsigned-5.11.0-34-generic-dbgsym
Filename: pool/main/l/linux-signed-hwe-5.11/linux-image-5.11.0-34-generic-dbgsym_5.11.0-34.36~20.04.1_amd64.ddeb
Size: 16556
MD5sum: de46adfcbf1550a8c8ea39dc41d55461
SHA1: 44c1efc1d9a409dbc9fcfeff3de4a2381eeb680b
SHA256: 469848f54b2b4e4d6e0de5e2f95ebfaefc185fcfe27564f8da2daa571f1c7fd2
SHA512: 2d26c09e2c555f334662dda73a568b2f338e3db6312d86069e2e824d7fe7482436d40fb8df4d87319906f2b9df871cdbc70dacaef59871125af9b290c240967e
Description: Signed kernel image generic
 A link to the debugging symbols for the generic signed kernel.
```

Problem is that this is different from previous, and working, 5.4.0-X and 5.8.0-X kernels. As you can see those packages are minimal in size (16556) and don't contain any debug data.

Summary: without the DWARF symbols for those kernels, the BTF files can't be generated.

I have already contacted Ubuntu kernel team and the conversation was:

```
10:16 AM <rafaeldtinoco> Im getting "E: Package 'linux-image-unsigned-5.11.0-34-generic-dbgsym' has no installation candidate" in ubuntu focal. 
10:18 AM <rafaeldtinoco> looks like I can get dbgsyms for aws kernels, for example, but not for -generic- ones
10:19 AM <rafaeldtinoco> linux-image-5.11.0-27-generic-dbgsym
10:19 AM <rafaeldtinoco> linux-image-5.11.0-22-generic-dbgsym
10:19 AM <rafaeldtinoco> linux-image-5.11.0-25-generic-dbgsym
10:19 AM <rafaeldtinoco> linux-image-5.11.0-34-generic-dbgsym
10:21 AM <rafaeldtinoco> unsigned ones are empty, the signed ones dont seem to exist fyi ^ 
10:22 AM <rafaeldtinoco> 5.4 and 5.8 hwe kernels are good
10:26 AM <klebers> rafaeldtinoco, hey! we are aware of the issue and it's on our list to fix it
10:26 AM <rafaeldtinoco> klebers: oh, great then. thanks!
```

I'll keep this issue opened here if anyone else faces the issue. Will close when this is solved.

**Comment by rafaeldtinoco** [comment]
For anyone facing this, it looks like 5.13 kernel is already being delivered as HWE kernel for Ubuntu Focal... and it has embedded BTF support (there won't be a need to have Ubuntu Focal 5.13 HWE kernels in BTFHub).

**Comment by acybere** [comment]
Nearly the same issue also exists for 4.18 kernels. For instance, with 'linux-image-4.18.0-15-generic', there is no x86_64 debug symbols package.
`# apt-cache search linux-image-4.18.0-15-generic*
linux-image-4.18.0-15-generic - Signed kernel image generic
linux-image-4.18.0-15-generic-dbgsym - Linux kernel debug image for version 4.18.0 on 32 bit x86 SMP`

**Comment by rafaeldtinoco** [comment]
For the record: The "broken" kernels are:

```
5.11.0-22-generic.failed
5.11.0-25-generic.failed
5.11.0-27-generic.failed
5.11.0-34-generic.failed
5.11.0-36-generic.failed
5.11.0-37-generic.failed
5.11.0-38-generic.failed
5.11.0-40-generic.failed
5.11.0-41-generic.failed
5.11.0-43-generic.failed
5.11.0-44-generic.failed
5.11.0-46-generic.failed
```

But the other 5.11 kernel flavors (azure, aws, gcp) are good to be used. I'll go ahead and close this (and keep the bug for the record).
