### ISSUE TITLE
Go version of update.sh?

### ISSUE THREAD

**Issue by brycekahle** [aquasecurity/btfhub#57]
Would you be open to a Go version of the `update.sh` script? For some distros (RHEL, Oracle) the BTF generation is the majority of the time, so parallelizing the kernel download and BTF generation would drastically speed things up.

**Comment by rafaeldtinoco** [comment]
I thought about it already, so, definitely. The project got bigger and bigger and update.sh is very ugly now, so, yep, let's do it. If you provide something I can definitely review and we go from there.

**Comment by brycekahle** [comment]
Sounds good! I'll hopefully have an initial version up for review in the next day or two.

**Comment by rafaeldtinoco** [comment]
And I'll pick a full day for going through btfhub and btfhub-archive entirely (even the documentation). I have been lazy with it lately because of other projects, I'm thankful you're now helping, really appreciated.

**Comment by brycekahle** [comment]
#62
