### ISSUE TITLE
Supporting multiple architectures

### ISSUE THREAD

**Issue by saschagrunert** [aquasecurity/btfhub#7]
Hey folks, do you think it would make sense to support multiple architectures within this repository, for example arm 64 bit?

**Comment by rafaeldtinoco** [comment]
I'm currently working on this issue. Will upload arm64 kernel BTFs once they're fully calculated.

**Comment by rafaeldtinoco** [comment]
Okay, I'll go ahead and close as I think we're done. I have added arm64 BTF files for all existing supported kernels and will keep submitting new ones until Ubuntu HWE kernels start to support BTF (by EOY, likely). Then the BTFHub will serve as a "legacy" kernels support repository if there aren't any other distros needing this type of hub.

Thanks!
