### ISSUE TITLE
ddeb leftovers in the daily runs

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/btfhub#74]
The new golang update app seems to be leaving .ddeb leftovers:

https://github.com/aquasecurity/btfhub/actions/runs/4349701197/jobs/7599658679

![image](https://user-images.githubusercontent.com/7395852/223333863-aa2eb713-9e21-4292-8a78-2b27e72546f2.png)

This could be mitigated by not syncing the ddebs or checking why the leftovers were there in the first place.

**Comment by rafaeldtinoco** [comment]
This only seems to happen when btfhub binary exists with unfinished extraction jobs. It is okay but then rsync should ignore other files (than .tar.gz BTF ones).

**Comment by brycekahle** [comment]
I think we could update the `.gitignore` in btfhub-archive to ignore `.ddeb` files and others

**Comment by brycekahle** [comment]
I took at pass at this in https://github.com/aquasecurity/btfhub-archive/pull/37
