### ISSUE TITLE
Reproducible BTF tarballs

### ISSUE THREAD

**Issue by brycekahle** [aquasecurity/btfhub#98]
I believe that if you removed a BTF `.tar.xz` file and re-ran the script, you would get a different output. The actual BTF *should* be the same, but because `tar` is preserving mtime, users, and possible other data, the `.tar.xz` file will always be different.

I can see two potential avenues to explore:
1. Extract a datetime from the package repo to use as the mtime for the BTF file itself
2. Force the same datetime for all files. This [StackOverflow answer](https://stackoverflow.com/a/54908072) talks about a way to do that.

WDYT?

**Comment by brycekahle** [comment]
For context, I think this is valuable so we can re-run the script on the archive when things change, such as `pahole` arguments, and only update what actually changes.

**Comment by rafaeldtinoco** [comment]
Sorry has been some busy last weeks. I wonder if the BTF ids coming from pahole won't be random. From libbpf, the BTF ids are created as the types are added to the "BTF" object.

I believe pahole has this process parallelized which would cause the IDs to, maybe, be different from one run to another.

**Comment by brycekahle** [comment]
https://github.com/acmel/dwarves/issues/42
